export * from './home';//首页
export * from './login'//登录
export * from './topic'//专题
export * from './topDetaile'//商品详情
export * from './type'//分类
export * from './my'//我的
export * from './seach'//查询
export * from './address'//地址
export * from './cart'//购物车